coverage:
  range: "50...75"
  status:
    patch: off
    project:
      default:
        target: 80%
        threshold: 2%
      unit:
        flags: unit
        target: 60%
        threshold: 2%
      integration:
        flags: integration
        target: 90%
        threshold: 2%

ignore:
  - "*_test.py"

comment:
  layout: "header, diff, flags"
