coverage:
  range: "50...75"
  status:
    project:
      default:
        target: 80%
        threshhold: null
      unit:
        flags: unit
        target: 60%
      integration:
        flags: integration
        target: 90%

ignore:
  - "*_test.py"
