name: deploy_docs

on:
  push:
    branches: [ deploy_docs ]
    
jobs:
  publish:
    steps:
    - uses: actions/checkout@v2
    # publish to a branch in current repo using GITHUB_TOKEN and other default settings
    - uses: oleksiyrudenko/gha-git-credentials@v1
      with:
        token: '${{ secrets.GITHUB_TOKEN }}'
    - run: |
        yarn run build
        yarn run deploy
  deploy_site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
        
      - name: install dependencies
        run: |
          pip install --upgrade pip
          pip install cython
          pip install -r dev_requirements.txt
      - name: Deploy mkdocs
        run: mkdocs gh-deploy
