name: deploy_docs

on:
  push:
    branches: [ deploy_docs ]
    
jobs:
  deploy_site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Set up credentials
        uses: oleksiyrudenko/gha-git-credentials@v1
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          actor: '${{ github.actor }}'
        
      - name: install dependencies
        run: |
          pip install --upgrade pip
          pip install cython
          pip install -r dev_requirements.txt
          pip install -r requirements.txt

      - name: Deploy mkdocs
        run: |
          git remote add gh-token "https://${{ secrets.GH_TOKEN}}@github.com/:user/:repo.git"
          git fetch gh-token && git fetch gh-token gh-pages:gh-pages
          mkdocs gh-deploy -v
