name: Publish Docker Container

on:
  push:
    # Publish `develop` as Docker `latest` image.
    branches:
      - develop
      - use-paraml

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

    paths:
      - requirements.txt
      - .github/workflows/publish-container.yml

  # Run tests for any PRs.
  pull_request:
    paths:
      - requirements.txt
      - .github/workflows/publish-container.yml

env:
  IMAGE_NAME: titanenv

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log into registry
        if: github.event_name == 'push'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push image
        if: github.event_name == 'push'
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix from version
          VERSION=latest
          # Strip "v" prefix from tag name and use that as version if exists
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

      - name: Push to Docker Hub
        if: github.event_name == 'push'
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: brownccv/titanenv
          tag_with_ref: true
